--- # ---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: web-app-ing
#   annotations:
#     ingress.kubernetes.io/rewrite-target: /
# spec:
#   backend:
#     serviceName: web-app-svc
#     servicePort: 80
#   rules:
#   - host: lenovo
#     http:
#       paths:
#       - path: /web-app
#         backend:
#           serviceName: web-app-svc
#           servicePort: 80
apiVersion: v1
kind: Service
metadata:
  name: web-app-svc
  labels:
    app: web-app
spec:
  type: NodePort
  ports:
    - name: http-port
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: web-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  selector:
    matchLabels:
      app: web-app
  replicas: 2
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: snowsystem/web-app:1.0.0
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
